export const CHANGE_USER_SUCCESS = 'CHANGE_USER_SUCCESS';
export const CHANGE_USER_REQUEST = 'CHANGE_USER_REQUEST';
export const CHANGE_USER_ERROR = 'CHANGE_USER_ERROR';

export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_ERROR = 'ADD_CATEGORY_ERROR';

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

export const ADD_IMAGE_SUCCESS = 'ADD_IMAGE_SUCCESS';
export const ADD_IMAGE_REQUEST = 'ADD_IMAGE_REQUEST';
export const ADD_IMAGE_ERROR = 'ADD_IMAGE_ERROR';

export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_ID_SUCCESS = 'GET_IMAGES_ID_SUCCESS';